language: clojure
lein: 2.9.1
dist: bionic
sudo: required
script:
  - ./ext/travisci/test.sh
  - $TRAVIS_BUILD_DIR/ext/travisci/secscan.sh "$TRAVIS_BUILD_DIR/src/clj" "clj"
matrix:
  include:
    - stage: puppetserver tests
      env: JRUBY_VERSION=9k
      jdk: openjdk8
    - stage: puppetserver tests
      env: JRUBY_VERSION=1.7
      jdk: openjdk8
notifications:
  email: false
  hipchat:
    rooms:
      secure: ASvt1XwEYbgkKuYZjZHytwg/6Y53Tg4T7QhohiDB4Xb1dmJueqPFpV2ko/VjHCa18JjLiUq0nWcDpRjsqaGGvJ5FSxTyyWDKtZsg1sUf4F+7aZ5vq0Dzg8Uzvdu7m9X1Uszvs9zf6wJ+Jobq4xck1xpPYxFT/+ei2Q2STrJ9xwQ=
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view: %{compare_url}"
      - "Build details: %{build_url}"
